name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test contracts
    defaults:
      run:
        working-directory: ./src/contracts
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install tox requests
    - name: Run tests and collect coverage
      run: tox -e coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3